### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by margarethaley** [operate-first/community-handbook#13]
**Describe the task that is missing from the handbook**

Handbook is missing a table of contents. We need to provide a table of contents so that anyone can look at the handbook and easily see what information they can find in it. 

**Have you discovered a solution to this task?**

N/a

**If you've discovered a solution, would you be willing to contribute it to the handbook?**
Not a solution, but I can write it and add it to the handbook.

**Comment by quaid** [comment]
This is the moment when we need to understand and/or decide tooling for converting from Markdown files to a webpage.

This should be handled by the GitHub Pages process. We should be able to hand it the source for a "book" as as Markdown file with an organized table of contents of (all the) .md files.

For now, let's start a mock-ToC for what we have and what we want to have. We can put in stubs for content that doesn't exist, too. For some ideas, we can look to the [slidedeck from Nuritzi & Jaskirat](https://docs.google.com/presentation/d/1l0spKW4OvPxMMcOdxx_Vzm0e0l0U5Y54kNMKpqCdz7Q/edit#slide=id.gde05202eb2_0_87) that has these suggested areas:

About: Mission, Vision, Values, History, Governance model, Code of Conduct

Teams/Groups: how to onboard onto each team, and specific processes that they follow

Handbook: How to use the handbook

Social: How to meet other community members and tools you use to communicate

Another slide notes these topics in their handbook:

About 
Community 
Contributing
Mentorship

That is also in the [CHAOSS repo for testing GitBook](https://github.com/chaoss/community-handbook).

Maybe a short meeting to or Slack with whiteboard to get some clarity on all this? I wonder who else in the community is interested in documentation tools and knows a bit about what can be done with GitHub Pages?
