### ISSUE TITLE
Gather a cumulative list of current docs in the Operate First community

### ISSUE THREAD

**Issue by stefwrite** [operate-first/community-handbook#31]
From the Contrib_X Docs WG:

We need to list all the doc resources we currently have in the Operate First community.

We'll track progress on this here on the Community Handbook board https://github.com/orgs/operate-first/projects/20

ACTION: We are using this issue to collect that list along with the list of who they're targeting.

OUTCOME NEEDED: List of docs that we already have and information about who those docs are targeting.

All community members are invited to add to the list of known docs in the community by commenting here on this issue.

**Comment by quaid** [comment]
# Baseline contrib docs

## Contribution process
https://github.com/operate-first/common/blob/main/docs/add_repo.md
https://github.com/operate-first/common/blob/main/docs/add_gh_member_and_access.md
https://github.com/operate-first/community-handbook/tree/main/content
https://github.com/operate-first/community-handbook/blob/main/content/how-to-request-a-repository.md
https://github.com/operate-first/community-handbook/blob/main/content/how-to-use-community-centric-labels.md
https://github.com/operate-first/community-handbook/blob/main/content/how-to-use-o1-clone-tool.md

## Contributing to the handbook
https://github.com/operate-first/community-handbook/tree/main/contributing
https://github.com/operate-first/community-handbook/blob/main/contributing/beginners-get-started.md
https://github.com/operate-first/community-handbook/blob/main/contributing/handbook-reviewer-guidelines.md
https://github.com/operate-first/community-handbook/blob/main/contributing/style-guide.md
https://github.com/operate-first/community-handbook/blob/main/contributing/template-handbook-article.md
https://github.com/operate-first/community/blob/main/contributing.md

## Operationshttps://github.com/operate-first/common/blob/main/docs/add_repo.md
https://github.com/operate-first/operations/tree/master/sli-slo#readme
https://github.com/operate-first/operations/tree/master/incident-management
https://github.com/operate-first/operations/blob/master/incident-management/README.md
https://github.com/operate-first/operations/blob/master/incident-management/configure-prometheus-alerts.md
https://github.com/operate-first/operations/blob/master/incident-management/github-receiver-setup.md
https://github.com/operate-first/operations/blob/master/incident-management/incident-management-procedure.md

# General information
https://github.com/operate-first/community/blob/main/open-source-services.md
