### ISSUE TITLE
Define practices for running a SIG

### ISSUE THREAD

**Issue by quaid** [operate-first/community-handbook#35]

**Comment by durandom** [comment]
Let's a have a small set of best practices on how to run a SIG and add that to the community handbook.
Maybe there's already something like that in gitlab or other communities

## open forum
* at the beginning, let people add items to the agenda

## populate the agenda
* start with an issue to the SIG board and discuss there
* add the issue to the agenda, if it needs more discussion
* form a subproject, work on the issue or defer work

## ceremony
* always capture notes from the beginning hackmd.io

**Comment by quaid** [comment]
> ## ceremony
> * always capture notes from the beginning hackmd.io

I'm having an idea, something like this:

1. Meeting facilitator does not keep notes, but does summarize points and actions as we move through the agenda.
1. Note taking is a rotating assignment, and primarily consists of filling out the template and capturing the facilitators some reason actions. The note taker is welcome to do more, but the bare minimum should be enabled by the facilitator so that it's easier for people who are less comfortable with ad hoc note-taking.
1. This all fits directly in with the template. Some of this idea is inspired by how meetbot works in IRC to capture special keywords and automatically turn those into meeting notes. So the idea here is a kind of verbal version of that, with a note taker serves as the meeybot by listening / watching out for keywords.

**Comment by schwesig** [comment]
I like like this approach a lot, just trying to figure out, what are the keywords, how to define, and who defines them.
And: Are keywords enough? What if a creative meeting to widen the scope brings new "keywords".
Maybe I am already to complicated.
Let's start with that, and hope the note taker is a ML/AI capable meeybot :-)
