### ISSUE TITLE
Create page describing all project repos - purpose, what goes there, etc.

### ISSUE THREAD

**Issue by quaid** [operate-first/community-handbook#36]

**Comment by Gregory-Pereira** [comment]
@quaid, are we still working towards this or can I close this? Seems to be related to documentation so i will also be tagging it as such.
/label kind/documentation
/remove-lifecycle stale

**Comment by quaid** [comment]
Hey @Gregory-Pereira this is indeed documentation and it's also a design need so it's a bit of a feature -- highlight of the site.

There are a handful of feature-like needs related to this for Open Source developers.
